

CREATE SCHEMA IF NOT EXISTS WEATHER;


CREATE TABLE IF NOT EXISTS  WEATHER.LOCATIONS (
	LOCATION_ID SMALLSERIAL PRIMARY KEY,
	CITY_NAME TEXT NOT NULL,
	COUNTRY_CODE CHAR(2) NOT NULL,
	LATITUDE NUMERIC(8, 4) NOT NULL,
	LONGITUDE NUMERIC(8, 4) NOT NULL,
	CONSTRAINT CITY_COUNTRY_UNIQUE UNIQUE (CITY_NAME, COUNTRY_CODE)
);



CREATE TABLE IF NOT EXISTS  WEATHER.PIPELINE_RUNS (
	RUN_ID UUID PRIMARY KEY,
	STARTED_AT TIMESTAMPTZ NOT NULL,
	FINISHED_AT TIMESTAMPTZ,
	STATUS TEXT NOT NULL,
	RECORDS_EXTRACTED INTEGER NOT NULL DEFAULT 0,
	RECORDS_LOADED INTEGER NOT NULL DEFAULT 0,
	ERROR_MESSAGE TEXT,
	CONSTRAINT STATUS_CHECK CHECK (
		STATUS LIKE 'RUNNING'
		OR STATUS LIKE 'SUCCESS'
		OR STATUS LIKE 'PARTIAL'
		OR STATUS LIKE 'FAILED'
	)
);


CREATE TABLE IF NOT EXISTS  WEATHER.OBSERVATIONS (
	OBSERVATION_ID BIGSERIAL PRIMARY KEY,
	RUN_ID UUID NOT NULL REFERENCES WEATHER.PIPELINE_RUNS (RUN_ID),
	LOCATION_ID SMALLINT NOT NULL REFERENCES WEATHER.LOCATIONS (LOCATION_ID),
	OBSERVED_AT TIMESTAMPTZ NOT NULL,
	EXTRACTED_AT TIMESTAMPTZ NOT NULL,
	TEMPERATURE_C NUMERIC(5, 2) NOT NULL,
	RELATIVE_HUMIDITY_PCT SMALLINT NOT NULL,
	SURFACE_PRESSURE_HPA NUMERIC(7, 2) NOT NULL,
	WIND_SPEED_KMH NUMERIC(6, 2) NOT NULL,
	WEATHER_CODE SMALLINT NOT NULL,
	RAW_FILE_PATH TEXT NOT NULL,
	CONSTRAINT CHECK_TEMP CHECK (TEMPERATURE_C BETWEEN -60 AND 60),
	CONSTRAINT CHECK_RHP CHECK (RELATIVE_HUMIDITY_PCT BETWEEN 0 AND 100),
	CONSTRAINT CHECK_SPH CHECK (SURFACE_PRESSURE_HPA BETWEEN 800 AND 1100),
	CONSTRAINT CHECK_WIND_SPEED CHECK (WIND_SPEED_KMH >= 0),
	CONSTRAINT OBS_LOC_UNIQUE UNIQUE (LOCATION_ID, OBSERVED_AT)
);