INSERT INTO
	WEATHER.LOCATIONS (CITY_NAME, COUNTRY_CODE, LATITUDE, LONGITUDE)
VALUES
	('Mostar', 'BA', 43.3438, 17.8078)
ON CONFLICT (CITY_NAME, COUNTRY_CODE) DO NOTHING;

INSERT INTO
	WEATHER.LOCATIONS (CITY_NAME, COUNTRY_CODE, LATITUDE, LONGITUDE)
VALUES
	('Sarajevo', 'BA', 43.8563, 18.4131)
ON CONFLICT (CITY_NAME, COUNTRY_CODE) DO NOTHING;

INSERT INTO
	WEATHER.LOCATIONS (CITY_NAME, COUNTRY_CODE, LATITUDE, LONGITUDE)
VALUES
	('Zagreb', 'HR', 45.8150, 15.9819)
ON CONFLICT (CITY_NAME, COUNTRY_CODE) DO NOTHING;