-- Daily average temperature per city

SELECT
	DATE_TRUNC('day', WO.OBSERVED_AT AT TIME ZONE 'UTC') AS OBSERVATION_DAY_UTC,
	WL.CITY_NAME,
	ROUND(AVG(WO.TEMPERATURE_C), 2)
FROM
	WEATHER.OBSERVATIONS AS WO
	JOIN WEATHER.LOCATIONS AS WL ON WO.LOCATION_ID = WL.LOCATION_ID
GROUP BY
	DATE_TRUNC('day', WO.OBSERVED_AT AT TIME ZONE 'UTC'),
	WL.CITY_NAME;


-- Latest weather snapshot per city
WITH
	SNAPSHOTS AS (
		SELECT
			WL.CITY_NAME AS CITY_NAME,
			WO.OBSERVED_AT AS OBSERVED_AT,
			WO.TEMPERATURE_C AS TEMPERATURE_C,
			WO.RELATIVE_HUMIDITY_PCT AS RELATIVE_HUMIDITY_PCT,
			WO.SURFACE_PRESSURE_HPA AS SURFACE_PRESSURE_HPA,
			WO.WIND_SPEED_KMH AS WIND_SPEED_KMH,
			WO.WEATHER_CODE AS WEATHER_CODE,
			ROW_NUMBER() OVER (
				PARTITION BY
					WL.CITY_NAME
				ORDER BY
					WO.OBSERVED_AT DESC
			) AS SNAPSHOT_RANK
		FROM
			WEATHER.LOCATIONS AS WL
			JOIN WEATHER.OBSERVATIONS AS WO ON WO.LOCATION_ID = WL.LOCATION_ID
	)
SELECT
	S.CITY_NAME,
	S.OBSERVED_AT,
	S.TEMPERATURE_C,
	S.RELATIVE_HUMIDITY_PCT,
	S.SURFACE_PRESSURE_HPA,
	S.WIND_SPEED_KMH,
	S.WEATHER_CODE
FROM
	SNAPSHOTS AS S
WHERE
	S.SNAPSHOT_RANK = 1;



-- Pipeline health
SELECT
	STATUS,
	COUNT(*),
	ROUND(AVG(RECORDS_LOADED), 2) AS AVG_RECORDS,
	MAX(STARTED_AT) AS LAST_STARTED_AT
FROM
	WEATHER.PIPELINE_RUNS
GROUP BY
	STATUS;


-- Duplicate check (location_id,observed_at)
SELECT
	LOCATION_ID,
	OBSERVED_AT,
	COUNT(*)
FROM
	WEATHER.OBSERVATIONS
GROUP BY
	LOCATION_ID,
	OBSERVED_AT
HAVING
	COUNT(*) > 1;

-- Invalid value check(temperature,humidity,pressure,wind speed)
SELECT
	*
FROM
	WEATHER.OBSERVATIONS
WHERE
	TEMPERATURE_C NOT BETWEEN -60 AND 60
	OR RELATIVE_HUMIDITY_PCT NOT BETWEEN 0 AND 100
	OR SURFACE_PRESSURE_HPA NOT BETWEEN 800 AND 1100
	OR WIND_SPEED_KMH < 0;

-- Ensuring every observation has an existing location and run_id
SELECT
	WO.OBSERVATION_ID
FROM
	WEATHER.OBSERVATIONS AS WO
WHERE
	WO.LOCATION_ID NOT IN (
		SELECT
			LOCATION_ID
		FROM
			WEATHER.LOCATIONS
	)
	OR WO.RUN_ID NOT IN (
		SELECT
			RUN_ID
		FROM
			WEATHER.PIPELINE_RUNS
	);